name: "Maven Build"

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn --file pom.xml

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: target
